// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package ru.spbau.mit.belyaev.message;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TextMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>optional string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code TextMessage}
   */
  public  static final class TextMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TextMessage)
      TextMessageOrBuilder {
    // Use TextMessage.newBuilder() to construct.
    private TextMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextMessage() {
      time_ = 0L;
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TextMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              time_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_TextMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_TextMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.mit.belyaev.message.Proto.TextMessage.class, ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>optional int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <code>optional string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>optional string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.mit.belyaev.message.Proto.TextMessage)) {
        return super.equals(obj);
      }
      ru.spbau.mit.belyaev.message.Proto.TextMessage other = (ru.spbau.mit.belyaev.message.Proto.TextMessage) obj;

      boolean result = true;
      result = result && (getTime()
          == other.getTime());
      result = result && getText()
          .equals(other.getText());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.mit.belyaev.message.Proto.TextMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TextMessage)
        ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_TextMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_TextMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.mit.belyaev.message.Proto.TextMessage.class, ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder.class);
      }

      // Construct using ru.spbau.mit.belyaev.message.Proto.TextMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_TextMessage_descriptor;
      }

      public ru.spbau.mit.belyaev.message.Proto.TextMessage getDefaultInstanceForType() {
        return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
      }

      public ru.spbau.mit.belyaev.message.Proto.TextMessage build() {
        ru.spbau.mit.belyaev.message.Proto.TextMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.mit.belyaev.message.Proto.TextMessage buildPartial() {
        ru.spbau.mit.belyaev.message.Proto.TextMessage result = new ru.spbau.mit.belyaev.message.Proto.TextMessage(this);
        result.time_ = time_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.mit.belyaev.message.Proto.TextMessage) {
          return mergeFrom((ru.spbau.mit.belyaev.message.Proto.TextMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.mit.belyaev.message.Proto.TextMessage other) {
        if (other == ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.mit.belyaev.message.Proto.TextMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.mit.belyaev.message.Proto.TextMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TextMessage)
    }

    // @@protoc_insertion_point(class_scope:TextMessage)
    private static final ru.spbau.mit.belyaev.message.Proto.TextMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.mit.belyaev.message.Proto.TextMessage();
    }

    public static ru.spbau.mit.belyaev.message.Proto.TextMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextMessage>
        PARSER = new com.google.protobuf.AbstractParser<TextMessage>() {
      public TextMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TextMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextMessage> getParserForType() {
      return PARSER;
    }

    public ru.spbau.mit.belyaev.message.Proto.TextMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.mit.belyaev.message.Proto.UserInfo.class, ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.mit.belyaev.message.Proto.UserInfo)) {
        return super.equals(obj);
      }
      ru.spbau.mit.belyaev.message.Proto.UserInfo other = (ru.spbau.mit.belyaev.message.Proto.UserInfo) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.mit.belyaev.message.Proto.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserInfo)
        ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.mit.belyaev.message.Proto.UserInfo.class, ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder.class);
      }

      // Construct using ru.spbau.mit.belyaev.message.Proto.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_UserInfo_descriptor;
      }

      public ru.spbau.mit.belyaev.message.Proto.UserInfo getDefaultInstanceForType() {
        return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
      }

      public ru.spbau.mit.belyaev.message.Proto.UserInfo build() {
        ru.spbau.mit.belyaev.message.Proto.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.mit.belyaev.message.Proto.UserInfo buildPartial() {
        ru.spbau.mit.belyaev.message.Proto.UserInfo result = new ru.spbau.mit.belyaev.message.Proto.UserInfo(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.mit.belyaev.message.Proto.UserInfo) {
          return mergeFrom((ru.spbau.mit.belyaev.message.Proto.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.mit.belyaev.message.Proto.UserInfo other) {
        if (other == ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.mit.belyaev.message.Proto.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.mit.belyaev.message.Proto.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserInfo)
    }

    // @@protoc_insertion_point(class_scope:UserInfo)
    private static final ru.spbau.mit.belyaev.message.Proto.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.mit.belyaev.message.Proto.UserInfo();
    }

    public static ru.spbau.mit.belyaev.message.Proto.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    public ru.spbau.mit.belyaev.message.Proto.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TypingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Typing)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Typing}
   */
  public  static final class Typing extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Typing)
      TypingOrBuilder {
    // Use Typing.newBuilder() to construct.
    private Typing(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Typing() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Typing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_Typing_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_Typing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.mit.belyaev.message.Proto.Typing.class, ru.spbau.mit.belyaev.message.Proto.Typing.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.mit.belyaev.message.Proto.Typing)) {
        return super.equals(obj);
      }
      ru.spbau.mit.belyaev.message.Proto.Typing other = (ru.spbau.mit.belyaev.message.Proto.Typing) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Typing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.mit.belyaev.message.Proto.Typing prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Typing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Typing)
        ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Typing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Typing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.mit.belyaev.message.Proto.Typing.class, ru.spbau.mit.belyaev.message.Proto.Typing.Builder.class);
      }

      // Construct using ru.spbau.mit.belyaev.message.Proto.Typing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Typing_descriptor;
      }

      public ru.spbau.mit.belyaev.message.Proto.Typing getDefaultInstanceForType() {
        return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
      }

      public ru.spbau.mit.belyaev.message.Proto.Typing build() {
        ru.spbau.mit.belyaev.message.Proto.Typing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.mit.belyaev.message.Proto.Typing buildPartial() {
        ru.spbau.mit.belyaev.message.Proto.Typing result = new ru.spbau.mit.belyaev.message.Proto.Typing(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.mit.belyaev.message.Proto.Typing) {
          return mergeFrom((ru.spbau.mit.belyaev.message.Proto.Typing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.mit.belyaev.message.Proto.Typing other) {
        if (other == ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.mit.belyaev.message.Proto.Typing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.mit.belyaev.message.Proto.Typing) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Typing)
    }

    // @@protoc_insertion_point(class_scope:Typing)
    private static final ru.spbau.mit.belyaev.message.Proto.Typing DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.mit.belyaev.message.Proto.Typing();
    }

    public static ru.spbau.mit.belyaev.message.Proto.Typing getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Typing>
        PARSER = new com.google.protobuf.AbstractParser<Typing>() {
      public Typing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Typing(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Typing> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Typing> getParserForType() {
      return PARSER;
    }

    public ru.spbau.mit.belyaev.message.Proto.Typing getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .UserInfo userInfo = 1;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.UserInfo getUserInfo();
    /**
     * <code>optional .UserInfo userInfo = 1;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder getUserInfoOrBuilder();

    /**
     * <code>optional .TextMessage textMessage = 2;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.TextMessage getTextMessage();
    /**
     * <code>optional .TextMessage textMessage = 2;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder getTextMessageOrBuilder();

    /**
     * <code>optional .Typing typing = 3;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.Typing getTyping();
    /**
     * <code>optional .Typing typing = 3;</code>
     */
    ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder getTypingOrBuilder();

    public ru.spbau.mit.belyaev.message.Proto.Message.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder subBuilder = null;
              if (typeCase_ == 1) {
                subBuilder = ((ru.spbau.mit.belyaev.message.Proto.UserInfo) type_).toBuilder();
              }
              type_ =
                  input.readMessage(ru.spbau.mit.belyaev.message.Proto.UserInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ru.spbau.mit.belyaev.message.Proto.UserInfo) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 1;
              break;
            }
            case 18: {
              ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder subBuilder = null;
              if (typeCase_ == 2) {
                subBuilder = ((ru.spbau.mit.belyaev.message.Proto.TextMessage) type_).toBuilder();
              }
              type_ =
                  input.readMessage(ru.spbau.mit.belyaev.message.Proto.TextMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ru.spbau.mit.belyaev.message.Proto.TextMessage) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 2;
              break;
            }
            case 26: {
              ru.spbau.mit.belyaev.message.Proto.Typing.Builder subBuilder = null;
              if (typeCase_ == 3) {
                subBuilder = ((ru.spbau.mit.belyaev.message.Proto.Typing) type_).toBuilder();
              }
              type_ =
                  input.readMessage(ru.spbau.mit.belyaev.message.Proto.Typing.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ru.spbau.mit.belyaev.message.Proto.Typing) type_);
                type_ = subBuilder.buildPartial();
              }
              typeCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.mit.belyaev.message.Proto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.mit.belyaev.message.Proto.Message.class, ru.spbau.mit.belyaev.message.Proto.Message.Builder.class);
    }

    private int typeCase_ = 0;
    private java.lang.Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite {
      USERINFO(1),
      TEXTMESSAGE(2),
      TYPING(3),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 1: return USERINFO;
          case 2: return TEXTMESSAGE;
          case 3: return TYPING;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int USERINFO_FIELD_NUMBER = 1;
    /**
     * <code>optional .UserInfo userInfo = 1;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.UserInfo getUserInfo() {
      if (typeCase_ == 1) {
         return (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
    }
    /**
     * <code>optional .UserInfo userInfo = 1;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder getUserInfoOrBuilder() {
      if (typeCase_ == 1) {
         return (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
    }

    public static final int TEXTMESSAGE_FIELD_NUMBER = 2;
    /**
     * <code>optional .TextMessage textMessage = 2;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.TextMessage getTextMessage() {
      if (typeCase_ == 2) {
         return (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
    }
    /**
     * <code>optional .TextMessage textMessage = 2;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder getTextMessageOrBuilder() {
      if (typeCase_ == 2) {
         return (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
    }

    public static final int TYPING_FIELD_NUMBER = 3;
    /**
     * <code>optional .Typing typing = 3;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.Typing getTyping() {
      if (typeCase_ == 3) {
         return (ru.spbau.mit.belyaev.message.Proto.Typing) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
    }
    /**
     * <code>optional .Typing typing = 3;</code>
     */
    public ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder getTypingOrBuilder() {
      if (typeCase_ == 3) {
         return (ru.spbau.mit.belyaev.message.Proto.Typing) type_;
      }
      return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeCase_ == 1) {
        output.writeMessage(1, (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_);
      }
      if (typeCase_ == 3) {
        output.writeMessage(3, (ru.spbau.mit.belyaev.message.Proto.Typing) type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_);
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ru.spbau.mit.belyaev.message.Proto.Typing) type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.mit.belyaev.message.Proto.Message)) {
        return super.equals(obj);
      }
      ru.spbau.mit.belyaev.message.Proto.Message other = (ru.spbau.mit.belyaev.message.Proto.Message) obj;

      boolean result = true;
      result = result && getTypeCase().equals(
          other.getTypeCase());
      if (!result) return false;
      switch (typeCase_) {
        case 1:
          result = result && getUserInfo()
              .equals(other.getUserInfo());
          break;
        case 2:
          result = result && getTextMessage()
              .equals(other.getTextMessage());
          break;
        case 3:
          result = result && getTyping()
              .equals(other.getTyping());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (typeCase_) {
        case 1:
          hash = (37 * hash) + USERINFO_FIELD_NUMBER;
          hash = (53 * hash) + getUserInfo().hashCode();
          break;
        case 2:
          hash = (37 * hash) + TEXTMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getTextMessage().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TYPING_FIELD_NUMBER;
          hash = (53 * hash) + getTyping().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.mit.belyaev.message.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.mit.belyaev.message.Proto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        ru.spbau.mit.belyaev.message.Proto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.mit.belyaev.message.Proto.Message.class, ru.spbau.mit.belyaev.message.Proto.Message.Builder.class);
      }

      // Construct using ru.spbau.mit.belyaev.message.Proto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.mit.belyaev.message.Proto.internal_static_Message_descriptor;
      }

      public ru.spbau.mit.belyaev.message.Proto.Message getDefaultInstanceForType() {
        return ru.spbau.mit.belyaev.message.Proto.Message.getDefaultInstance();
      }

      public ru.spbau.mit.belyaev.message.Proto.Message build() {
        ru.spbau.mit.belyaev.message.Proto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.mit.belyaev.message.Proto.Message buildPartial() {
        ru.spbau.mit.belyaev.message.Proto.Message result = new ru.spbau.mit.belyaev.message.Proto.Message(this);
        if (typeCase_ == 1) {
          if (userInfoBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = userInfoBuilder_.build();
          }
        }
        if (typeCase_ == 2) {
          if (textMessageBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = textMessageBuilder_.build();
          }
        }
        if (typeCase_ == 3) {
          if (typingBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = typingBuilder_.build();
          }
        }
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.mit.belyaev.message.Proto.Message) {
          return mergeFrom((ru.spbau.mit.belyaev.message.Proto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.mit.belyaev.message.Proto.Message other) {
        if (other == ru.spbau.mit.belyaev.message.Proto.Message.getDefaultInstance()) return this;
        switch (other.getTypeCase()) {
          case USERINFO: {
            mergeUserInfo(other.getUserInfo());
            break;
          }
          case TEXTMESSAGE: {
            mergeTextMessage(other.getTextMessage());
            break;
          }
          case TYPING: {
            mergeTyping(other.getTyping());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.mit.belyaev.message.Proto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.mit.belyaev.message.Proto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int typeCase_ = 0;
      private java.lang.Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.UserInfo, ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder, ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          if (typeCase_ == 1) {
            return (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
        } else {
          if (typeCase_ == 1) {
            return userInfoBuilder_.getMessage();
          }
          return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(ru.spbau.mit.belyaev.message.Proto.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public Builder mergeUserInfo(ru.spbau.mit.belyaev.message.Proto.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (typeCase_ == 1 &&
              type_ != ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance()) {
            type_ = ru.spbau.mit.belyaev.message.Proto.UserInfo.newBuilder((ru.spbau.mit.belyaev.message.Proto.UserInfo) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 1) {
            userInfoBuilder_.mergeFrom(value);
          }
          userInfoBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
          }
          userInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder getUserInfoBuilder() {
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder getUserInfoOrBuilder() {
        if ((typeCase_ == 1) && (userInfoBuilder_ != null)) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 1) {
            return (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
        }
      }
      /**
       * <code>optional .UserInfo userInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.UserInfo, ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder, ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          if (!(typeCase_ == 1)) {
            type_ = ru.spbau.mit.belyaev.message.Proto.UserInfo.getDefaultInstance();
          }
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.spbau.mit.belyaev.message.Proto.UserInfo, ru.spbau.mit.belyaev.message.Proto.UserInfo.Builder, ru.spbau.mit.belyaev.message.Proto.UserInfoOrBuilder>(
                  (ru.spbau.mit.belyaev.message.Proto.UserInfo) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 1;
        onChanged();;
        return userInfoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.TextMessage, ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder, ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder> textMessageBuilder_;
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.TextMessage getTextMessage() {
        if (textMessageBuilder_ == null) {
          if (typeCase_ == 2) {
            return (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return textMessageBuilder_.getMessage();
          }
          return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public Builder setTextMessage(ru.spbau.mit.belyaev.message.Proto.TextMessage value) {
        if (textMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          textMessageBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public Builder setTextMessage(
          ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder builderForValue) {
        if (textMessageBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          textMessageBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public Builder mergeTextMessage(ru.spbau.mit.belyaev.message.Proto.TextMessage value) {
        if (textMessageBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance()) {
            type_ = ru.spbau.mit.belyaev.message.Proto.TextMessage.newBuilder((ru.spbau.mit.belyaev.message.Proto.TextMessage) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            textMessageBuilder_.mergeFrom(value);
          }
          textMessageBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public Builder clearTextMessage() {
        if (textMessageBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          textMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder getTextMessageBuilder() {
        return getTextMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder getTextMessageOrBuilder() {
        if ((typeCase_ == 2) && (textMessageBuilder_ != null)) {
          return textMessageBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .TextMessage textMessage = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.TextMessage, ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder, ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder> 
          getTextMessageFieldBuilder() {
        if (textMessageBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = ru.spbau.mit.belyaev.message.Proto.TextMessage.getDefaultInstance();
          }
          textMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.spbau.mit.belyaev.message.Proto.TextMessage, ru.spbau.mit.belyaev.message.Proto.TextMessage.Builder, ru.spbau.mit.belyaev.message.Proto.TextMessageOrBuilder>(
                  (ru.spbau.mit.belyaev.message.Proto.TextMessage) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        onChanged();;
        return textMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.Typing, ru.spbau.mit.belyaev.message.Proto.Typing.Builder, ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder> typingBuilder_;
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.Typing getTyping() {
        if (typingBuilder_ == null) {
          if (typeCase_ == 3) {
            return (ru.spbau.mit.belyaev.message.Proto.Typing) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
        } else {
          if (typeCase_ == 3) {
            return typingBuilder_.getMessage();
          }
          return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public Builder setTyping(ru.spbau.mit.belyaev.message.Proto.Typing value) {
        if (typingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          typingBuilder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public Builder setTyping(
          ru.spbau.mit.belyaev.message.Proto.Typing.Builder builderForValue) {
        if (typingBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          typingBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public Builder mergeTyping(ru.spbau.mit.belyaev.message.Proto.Typing value) {
        if (typingBuilder_ == null) {
          if (typeCase_ == 3 &&
              type_ != ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance()) {
            type_ = ru.spbau.mit.belyaev.message.Proto.Typing.newBuilder((ru.spbau.mit.belyaev.message.Proto.Typing) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 3) {
            typingBuilder_.mergeFrom(value);
          }
          typingBuilder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public Builder clearTyping() {
        if (typingBuilder_ == null) {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
          }
          typingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.Typing.Builder getTypingBuilder() {
        return getTypingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      public ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder getTypingOrBuilder() {
        if ((typeCase_ == 3) && (typingBuilder_ != null)) {
          return typingBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 3) {
            return (ru.spbau.mit.belyaev.message.Proto.Typing) type_;
          }
          return ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Typing typing = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.mit.belyaev.message.Proto.Typing, ru.spbau.mit.belyaev.message.Proto.Typing.Builder, ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder> 
          getTypingFieldBuilder() {
        if (typingBuilder_ == null) {
          if (!(typeCase_ == 3)) {
            type_ = ru.spbau.mit.belyaev.message.Proto.Typing.getDefaultInstance();
          }
          typingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.spbau.mit.belyaev.message.Proto.Typing, ru.spbau.mit.belyaev.message.Proto.Typing.Builder, ru.spbau.mit.belyaev.message.Proto.TypingOrBuilder>(
                  (ru.spbau.mit.belyaev.message.Proto.Typing) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 3;
        onChanged();;
        return typingBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final ru.spbau.mit.belyaev.message.Proto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.mit.belyaev.message.Proto.Message();
    }

    public static ru.spbau.mit.belyaev.message.Proto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public ru.spbau.mit.belyaev.message.Proto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Typing_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Typing_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\")\n\013TextMessage\022\014\n\004time\030\001" +
      " \001(\003\022\014\n\004text\030\002 \001(\t\"\030\n\010UserInfo\022\014\n\004name\030\001" +
      " \001(\t\"\010\n\006Typing\"p\n\007Message\022\035\n\010userInfo\030\001 " +
      "\001(\0132\t.UserInfoH\000\022#\n\013textMessage\030\002 \001(\0132\014." +
      "TextMessageH\000\022\031\n\006typing\030\003 \001(\0132\007.TypingH\000" +
      "B\006\n\004type2(\n\004Chat\022 \n\004chat\022\010.Message\032\010.Mes" +
      "sage\"\000(\0010\001B%\n\034ru.spbau.mit.belyaev.messa" +
      "geB\005Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextMessage_descriptor,
        new java.lang.String[] { "Time", "Text", });
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_Typing_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Typing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Typing_descriptor,
        new java.lang.String[] { });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "UserInfo", "TextMessage", "Typing", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
